### ISSUE TITLE
a questions about data simulation

### ISSUE THREAD

**Issue by perlatex** [lhbikos/ReC_MultivModel#2]
Dear Professor Lynette H. Bikos,
  
I hope this message finds you well. I've recently had the pleasure of reading your book, and I must say I truly enjoyed the content and your unique writing style.  
While going through the chapters,  I have a question concerning about data simulation for SEM in Chapter 5-11.  For example , in Chapter [8.4.1 Simulating the data from the journal article](https://lhbikos.github.io/ReC_MultivModel/ModMed.html#research-vignette-7),  corresponding to the correlation matrix from the [research vignette](https://doi.org/10.1037/cou0000231),

![p](https://github.com/lhbikos/ReC_MultivModel/assets/41543832/3fcdac78-5964-4d53-85da-b51f96328a57)

 the code in your book is

```r
Lewis_generating_model <- '
         GRMS ~ 0.20*Spirituality
         GRMS ~ 0.28*SocSupport
         GRMS ~ 0.30*Engagement
         GRMS ~ 0.41*Disengagement
         GRMS ~ 0.19*GRIC
         GRMS ~ -0.32*MntlHlth
         GRMS ~ -0.18*PhysHlth
         
         Spirituality ~ 0.49*SocSupport
         Spirituality ~ 0.57*Engagement
         Spirituality ~ 0.22*Disengagement
         Spirituality ~ 0.12*GRIC
         Spirituality ~ -0.06*MntlHlth
         Spirituality ~ -0.13*PhysHlth
'
```

According to my understanding, when both the variance of both two variables is 1, the correlation coefficient is equal to their covariance. Additionally, in the lavaan language,  `~` represents regression, and  `~~` represents covariance. **Therefore, I believe it should be ` ~~` instead of  `~`.**

```r
Lewis_generating_model <- '

         GRMS ~~ 0.20*Spirituality
         GRMS ~~ 0.28*SocSupport
         GRMS ~~ 0.30*Engagement
         GRMS ~~ 0.41*Disengagement
         GRMS ~~ 0.19*GRIC
         GRMS ~~ -0.32*MntlHlth
         GRMS ~~ -0.18*PhysHlth
         
         Spirituality ~~ 0.49*SocSupport
         Spirituality ~~ 0.57*Engagement
         Spirituality ~~ 0.22*Disengagement
         Spirituality ~~ 0.12*GRIC
         Spirituality ~~ -0.06*MntlHlth
         Spirituality ~~ -0.13*PhysHlth

'
```

I'm not sure if my understanding is correct. Looking forward to your response. 
Thank you very much.

**Comment by lhbikos** [comment]
Thank you so much for this comment.  When I looked at what you were suggesting, I immediately (also) saw the error. I have consulted a quantitative psychologist colleague. Together, we think that because I was working with correlation coefficients (i.e., standardized), the resulting simple regressions 'should be' identical to the the more properly specified correlations. I didn't notice the error because the resulting simulation worked well enough to work the problem.

I will put this on my to-do-list to fix -- but it will be several months because I'm swamped with other tasks.

Again, thank you so very much. I'm tickled that you are using the resource and I welcome any additional feedback.  ~Lynette
